default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: dsin_development


test:
  <<: *default
  database: dsin_test
  
production:
    <<: *default
    adapter: postgresql
    encoding: unicode
    database: myapp_production
    username: myapp
    password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>